Fixed PEP warnings
IBM/javacore-analyser pull request #75
Opened 2024-12-19 08:00 UTC by PiotrAniola82

2024-12-19 08:48 UTC, PiotrAniola82 commented
@kkazmierczyk ready for review

2024-12-19 10:28 UTC, kkazmierczyk requested changes
@PiotrAniola82 see my comments in that review.

2024-12-19 10:31 UTC, PiotrAniola82 commented on src/javacore_analyser/snapshot_collection_collection.py
> +    #    return self.snapshot_collections.__next__()
__next__ does not exist on snapshot collection. the only reason this wasn't causing an error, is because this method was never called.

2024-12-19 10:33 UTC, PiotrAniola82 commented on src/javacore_analyser/javacore_analyser_batch.py
> +        logging.error(ex)
This is to address the 'Too broad exception clause' warning. The warning goes away when you have a named object that you catch (ex, in this case), but then it also needs to be used to avoid another warning. 
Perhaps we should remove traceback.print_exc(file=sys.stdout) and just use 'logging' for logging.

2024-12-20 08:27 UTC, PiotrAniola82 commented on src/javacore_analyser/javacore_analyser_batch.py
> +        logging.error(ex)
Example output from logging.error:
```
2024-12-20 09:26:25,127 [thread: 6420][ERROR][javacore_analyser_batch.py:108] my message
2024-12-20 09:26:25,127 [thread: 6420][ERROR][javacore_analyser_batch.py:109] Processing was not successful. Correct the problem and try again. Exiting with error 13
Traceback (most recent call last):
  File "C:\Users\P40095820\PycharmProjects\javacore-analyser\src\javacore_analyser\javacore_analyser_batch.py", line 106, in main
    throw(Exception("my message"))
  File "C:\Users\P40095820\PycharmProjects\javacore-analyser\src\javacore_analyser\javacore_analyser_batch.py", line 115, in throw
    raise exception
Exception: my message
```

This is the same as for traceback.print_exc, so I will remove the latter.

2024-12-20 12:04 UTC, merged